### ISSUE TITLE
CF_Log???

### ISSUE THREAD

**Issue by EGDak24** [Arkensor/DayZ-CommunityFramework#134]
WIN-R9MK9FQUS30, 13.02 2023 15:34:00
Can't compile "Engine" script module!
DayZExpansion/Core/Scripts/1_Core/dayzexpansion_core\cf_trace.c(120): Unknown type 'CF_Log'
Runtime mode
CLI params: config D:\TCAFiles\Users\dakotag\9449404\Config.cfg ip 181.215.243.153 port 2302 mod @Dabs Framework;@Community-Online-Tools;@DayZ-Expansion-Licensed;@DayZ-Expansion-Bundle;@ZomBerry Admin Tools;@RedFalcon Flight System Heliz;@Equipment System;@GoreZ;@Drippy Sneakers;@LastDayZ_Radios servermod  profiles D:\TCAFiles\Users\dakotag\9449404\SC name SC BEpath D:\TCAFiles\Users\dakotag\9449404\SC\Battleye noFilePatching  limitFPS 0 

My serever is locked now......

**Comment by EGDak24** [comment]
Can't compile "Engine" script module!

DayZExpansion/Core/Scripts/1_Core/dayzexpansion_core\cf_trace.c(120): Unknown type 'CF_Log'

**Comment by Arkensor** [comment]
That is an issue the expansion team has to deal with.
