### ISSUE TITLE
CF Error after 1.20 DayZ update

### ISSUE THREAD

**Issue by mrangrybacon** [Arkensor/DayZ-CommunityFramework#136]
Hello, we are having an issue with the CF mod after we have updated to 1.20:

Can't compile "GameLib" script module!

JM/CF/Scripts/2_GameLib/communityframework\eventhandler\cf_eventhandler.c(83): Too many parameters for 'Invoke' method

CF was working before patch. We have also tested on a test server with just CF and got the same error. Can you please have a look into this? Thanks

**Comment by Arkensor** [comment]
Hello,
what other mods do you have installed? This error is potentially something they need to fix. The code in question seems to be correct and the error message is on the wrong line indicates, that some other mod is causing this. 

Please send the full stack trace of this.

**Comment by mrangrybacon** [comment]
Hi sorry, can you please clarify how we can get a stacktrace from the server? Is it one of the .rpt files?

**Comment by Pyxarik** [comment]
Hello @Arkensor, 

Same problem for me. I uninstalled all mods where "CF" is required. And I still get the same error.
↓

Can't compile "GameLib" script module!

JM/CF/Scripts/2_GameLib/communityframework\eventhandler\cf_eventhandler.c(79): Too many parameters for 'Invoke' method

Runtime mode
CLI params: config serverDZ.cfg.active port 2402 profiles profiles adminlog  freezecheck  dologs  mod @CF;@Iztek;@Iztek_Zarge;@GameLabs;@No Build Zones;@Code Lock;@GoreZ

Any idea ? :(

**Comment by Arkensor** [comment]
@mrangrybacon the full error message or perhaps even better the file .log file the error occurred in. We need more context.

**Comment by Arkensor** [comment]
@AtPaks please send me the workshop links of all the mods you are using, so I can try and reproduce the issue. Does this error happen also on the client or only on the server?

**Comment by Pyxarik** [comment]
@Arkensor 
It crashes as soon as I run. The server does not connect and does not turn on.

(CF Required) https://steamcommunity.com/sharedfiles/filedetails/?id=2303554682
https://steamcommunity.com/sharedfiles/filedetails/?id=2115602332
https://steamcommunity.com/sharedfiles/filedetails/?id=2109061314
(CF Required) https://steamcommunity.com/sharedfiles/filedetails/?id=1623711988
https://steamcommunity.com/sharedfiles/filedetails/?id=1648967877
https://steamcommunity.com/sharedfiles/filedetails/?id=2831742849
https://steamcommunity.com/sharedfiles/filedetails/?id=1646187754
https://steamcommunity.com/sharedfiles/filedetails/?id=2371483403
(CF Required) https://steamcommunity.com/sharedfiles/filedetails/?id=1828439124
https://steamcommunity.com/sharedfiles/filedetails/?id=2464526692
https://steamcommunity.com/sharedfiles/filedetails/?id=2841636171
(CF Required) https://steamcommunity.com/sharedfiles/filedetails/?id=2615342612
https://steamcommunity.com/sharedfiles/filedetails/?id=1559212036

You can try with & without "CF Required"' mods.

**Comment by Arkensor** [comment]
Heya @AtPaks as seen in another issue #139  validating your game should resolve your issues. See the issue or current cf workshop item description on what to do. Let me know if that also works for you.

**Comment by Pyxarik** [comment]
Hop @Arkensor 
I finally reinstalled everything (I'm using Omega Manager), and it works now.
Thank you for your help :)
