### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Troppo91** [Arkensor/DayZ-CommunityFramework#139]
JM/CF/Scripts/2_GameLib/communityframework\eventhandler\cf_eventhandler.c(79) Too many parameters for 'Invoke' cant compile error message.
Not sure if it is actually CF related but cant for the life work out whats going. Any help would be much apprecited.

**Comment by Arkensor** [comment]
Please post the full stacktrace

**Comment by Troppo91** [comment]
[script_2023-02-15_16-21-43.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/10741812/script_2023-02-15_16-21-43.log)
[crash_2023-02-15_16-21-43.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/10741813/crash_2023-02-15_16-21-43.log)
[rptlog.txt](https://github.com/Arkensor/DayZ-CommunityFramework/files/10741824/rptlog.txt)

**Comment by Troppo91** [comment]
Sorry not sure how to Aquire the stack trace. I can provide any other information needed though

**Comment by Arkensor** [comment]
Hey, what you posted in the script log is the stack trace, thank you. There are errors in it that should not be possible, even unrelated to CF. It's complaining about functions not existing in the game that are new in 1.20. So we suspect your installation might be corrupt. Validate your setup. Delete the server .exe file and dta folder and have steam validate the install, so it will download fresh correct copies of it. Then please try again without any other changes.

**Comment by Troppo91** [comment]
Your an absolute legend mate, did what you said and it all fired back up thanks heaps for your help

**Comment by Arkensor** [comment]
Thank you for the feedback. Glad we could help.
