### ISSUE TITLE
'CF_Path.GetFileNameWithoutExtension' returns a '.' and throws error

### ISSUE THREAD

**Issue by InclementDab** [Arkensor/DayZ-CommunityFramework#142]
Doing this:
![image](https://user-images.githubusercontent.com/6282778/224116417-9d3cc38c-eb6b-45e5-9f50-945b950250dc.png)

Results in this: 
![image](https://user-images.githubusercontent.com/6282778/224116468-5feefe0d-1d3a-4c00-aa75-6ed7e5237542.png)

**Comment by Arkensor** [comment]
Most likely caused by this copy paste error duplicate? @Jacob-Mango:
> fileName = fileName.Substring(0, **fileName.Length() - fileName.Length()** - index);
