### ISSUE TITLE
Requires DF_Scripts

### ISSUE THREAD

**Issue by AdrianDrak** [Arkensor/DayZ-CommunityFramework#160]
@
![Screenshot_438](https://github.com/Arkensor/DayZ-CommunityFramework/assets/163713956/ae94d2e9-882a-4c38-a32a-f45e071daaaf)
![Screenshot_439](https://github.com/Arkensor/DayZ-CommunityFramework/assets/163713956/4b48dcfa-5134-4d2d-857b-6afec62d44ba)
![Screenshot_440](https://github.com/Arkensor/DayZ-CommunityFramework/assets/163713956/fa378c72-d43d-4cb5-b060-9ed21b143130)
![Screenshot_441](https://github.com/Arkensor/DayZ-CommunityFramework/assets/163713956/579761f9-ae95-4573-9caa-9c89eba97b24)

**Comment by Arkensor** [comment]
Hello,
that not a problem with CF. You are looking for dabs framework. That is missing.
