### ISSUE TITLE
Mod abusse 

### ISSUE THREAD

**Issue by Lokyyyy11** [Arkensor/DayZ-CommunityFramework#161]
I want to start with a excuse ,my English is not that good.

I make this becouse my friend got banned for Ban evading  on NorthMen ,he was banned after one of our teametes got banned for "cheating".The ban evading is not given right and he is inccent, I make this becouse he is 45 years old and still learns to do this things 
I can explain this situation better on discord ,If  you may want to help us please conntact me on discord or here!

Best regards Loky
Discord:loky1607

**Comment by Arkensor** [comment]
This is a utility mod for DayZ, we are not involved at all with your bans. Did you mean to contact CFTools? If so, those are different people.
