### ISSUE TITLE
I've recently installed everything but return this error when start an Enfusion project

### ISSUE THREAD

**Issue by conceptfac** [Arkensor/DayZ-CommunityFramework#167]
![image](https://github.com/Arkensor/DayZ-CommunityFramework/assets/46586448/561e8eae-d3b8-4791-84ba-782f0d0ea688)

**Comment by Arkensor** [comment]
Delete the mod locally and re-subscribe. If that does not fix attach a full rpt log of an attempt so we can see all mods being used etc.
