### ISSUE TITLE
Function: 'SpawnObjects'

### ISSUE THREAD

**Issue by Glory-star** [Arkensor/DayZ-CommunityFramework#168]
I'm not sure if the problem is on your side, but it's possible. [::SpawnObjects] :: [ERROR] :: File "$mission:Map_Preset/Trade_Skalisty.json" does not exist, check the provided path
Function: 'SpawnObjects'
Stack trace:
scripts/3_Game/objectspawner.c:22
scripts/3_Game/objectspawner.c:65
scripts/3_Game/dayzgame.c:1108
scripts/3_Game/dayzgame.c:2873
JM/CF/Scripts/3_Game/communityframework\game\dayzgame.c:23
LBmaster_Core/scripts/3_Game/lbmaster_core\dayzgame.c:173 It takes the name from the 1st preset from cfggameplay which works correctly, it’s not a problem that it says it’s not there

**Comment by Arkensor** [comment]
Hello as the error message says, the file `$mission:Map_Preset/Trade_Skalisty.json` does not exist inside of your mission folder. Not a problem related to CF, the spawner code is vanilla.

**Comment by Glory-star** [comment]
> Hello as the error message says, the file `$mission:Map_Preset/Trade_Skalisty.json` does not exist inside of your mission folder. Not a problem related to CF, the spawner code is vanilla.

Well, the simple matter is that the file is there and it works, you know? that is, should I create a report on Bohemia?
