### ISSUE TITLE
MVC throwing warnings

### ISSUE THREAD

**Issue by Arkensor** [Arkensor/DayZ-CommunityFramework#29]
`SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<Object>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<bool>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<Widget>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<Observable>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<int>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<ScriptedViewBase>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<float>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<vector>.Cast' for safe down-casting
SCRIPT    (W): @"JM/CF/Scripts/3_Game/communityframework\mvc\typeconverter.c,115": Unsafe down-casting, use 'Param1<string>.Cast' for safe down-casting`

**Comment by InclementDab** [comment]
aware of these issues. at the time of writing it, doing `Param<T>.Cast(value)` would not successfully cast values, so these warnings were a necessary evil.

will try again on latest patch to see if anything is different

**Comment by Arkensor** [comment]
Maybe (Param<T>)value works? as in normal casting syntax?

**Comment by InclementDab** [comment]
https://github.com/Jacob-Mango/DayZ-Community-Framework/tree/bugfix/warnings

**Comment by InclementDab** [comment]
https://github.com/Jacob-Mango/DayZ-Community-Framework/tree/bugfix/warnings

**Comment by Arkensor** [comment]
https://github.com/Jacob-Mango/DayZ-Community-Framework/pull/31

**Comment by Arkensor** [comment]
Resolved with #31
