### ISSUE TITLE
 Bad type 'CF_XML'

### ISSUE THREAD

**Issue by tsalesproductions** [Arkensor/DayZ-CommunityFramework#32]
Can't compile 'game' script module! scripts/3_game/CommunityFramework/CommunityFramework.c(20): Bad type 'CF_XML'
Anyone else had this problem?

**Comment by dyzGBT** [comment]
> Can't compile 'game' script module! scripts/3_game/CommunityFramework/CommunityFramework.c(20): Bad type 'CF_XML'
> Anyone else had this problem?

Having this same issue when attempting to set up workbench environment and run.
