### ISSUE TITLE
Update MVC naming

### ISSUE THREAD

**Issue by Arkensor** [Arkensor/DayZ-CommunityFramework#41]
- Change MVC to MVB (Model View Binding)
- Update all added classes to the CF_Classname pattern e.g. ScriptViewTemplate -> CF_MVB_ScriptViewTemplate

**Comment by InclementDab** [comment]
The naming needs to stay, we've already gutted it enough

**Comment by Arkensor** [comment]
Re-opened - even if this is not addressed in the near future.

**Comment by Arkensor** [comment]
Resolved with #57
