### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by 0Subject0** [Arkensor/DayZ-CommunityFramework#54]
Log C:\SERVICES\ni1369531_1_SHARE\ftproot\dayzstandalone\config\script_2021-05-08_02-26-52.log started at 08.05. 02:27:04

SCRIPT       : Registered 258 temporary action enum(s), UAN==258
SCRIPT    (E): @"JM/CF/Scripts/3_Game/communityframework\communityframework.c,20": Bad type 'CF_XML'
SCRIPT    (E): @"JM/CF/Scripts/3_Game/communityframework\communityframework.c,20": Unknown type 'CF_XML'
SCRIPT    (E): Can't compile "Game" script module!

JM/CF/Scripts/3_Game/communityframework\communityframework.c(20): Bad type 'CF_XML'

**Comment by 0Subject0** [comment]
I have installed CF twice ,but it doesn't work.

**Comment by Arkensor** [comment]
There is nothing we can do about that. The issue is DayZ, not CF itself. Sorry.
